# Generated by Django 5.2 on 2026-05-16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("employee", "0005_alter_employee_phone_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeIndonesiaProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("npwp", models.CharField(blank=True, max_length=50, null=True, verbose_name="NPWP")),
                (
                    "nik",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="NIK (KTP/Paspor)",
                    ),
                ),
                (
                    "bpjs_kesehatan",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="BPJS Kesehatan"
                    ),
                ),
                (
                    "bpjs_ketenagakerjaan",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="BPJS Ketenagakerjaan",
                    ),
                ),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indonesia_profile",
                        to="employee.employee",
                    ),
                ),
            ],
        ),
    ]

