# Generated by Django 5.2 on 2026-05-16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_initial"),
        ("horilla_id", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PayrollPeriodSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payroll_period_type",
                    models.CharField(
                        choices=[
                            ("calendar_month", "Calendar Month (1-last)"),
                            ("custom_cutoff", "Custom Cutoff (e.g., 21-20)"),
                        ],
                        default="calendar_month",
                        max_length=30,
                    ),
                ),
                (
                    "cutoff_day",
                    models.PositiveSmallIntegerField(
                        default=20,
                        help_text="Used when payroll period type is Custom Cutoff (e.g., cutoff_day=20 means 21-20).",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(31),
                        ],
                    ),
                ),
                (
                    "monthly_salary_mode",
                    models.CharField(
                        choices=[
                            ("prorate_by_calendar_month", "Prorate by Calendar Month"),
                            ("full_period_as_one_month", "Full Period as One Payroll Month"),
                        ],
                        default="prorate_by_calendar_month",
                        help_text="How to calculate monthly salary when payslip period crosses calendar months.",
                        max_length=40,
                    ),
                ),
                (
                    "company",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.company",
                    ),
                ),
            ],
        ),
    ]

