# Generated by Django 5.2 on 2026-05-16

from django.db import migrations


def create_default_indonesia_filing_statuses(apps, schema_editor):
    FilingStatus = apps.get_model("payroll", "FilingStatus")

    default_codes = [
        "TK/0",
        "TK/1",
        "TK/2",
        "TK/3",
        "K/0",
        "K/1",
        "K/2",
        "K/3",
    ]

    for code in default_codes:
        FilingStatus.objects.update_or_create(
            filing_status=code,
            company_id=None,
            defaults={
                "based_on": "taxable_gross_pay",
                "use_py": True,
                "python_code": None,
                "description": f"Indonesia PTKP {code} (PPh21)",
            },
        )


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):
    dependencies = [
        ("payroll", "0003_alter_payrollsettings_position"),
        ("horilla_id", "0002_payrollperiodsetting"),
    ]

    operations = [
        migrations.RunPython(
            create_default_indonesia_filing_statuses, reverse_code=noop_reverse
        ),
    ]

