# Generated by Django 5.2 on 2026-05-16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Choice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name="DynamicField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=100)),
                ("verbose_name", models.CharField(max_length=30)),
                ("field_name", models.CharField(editable=False, max_length=30)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("1", "Character field"),
                            ("2", "Integer field"),
                            ("3", "Text field"),
                            ("4", "Date field"),
                            ("5", "File field"),
                        ],
                        max_length=50,
                    ),
                ),
                ("is_required", models.BooleanField(default=False)),
                ("remove_column", models.BooleanField(default=False)),
            ],
            options={
                "unique_together": {("model", "field_name")},
            },
        ),
        migrations.AddField(
            model_name="dynamicfield",
            name="choices",
            field=models.ManyToManyField(blank=True, to="dynamic_fields.choice"),
        ),
    ]

